# -*- coding: utf-8 -*-
"""Financial Fraud Analytics & Risk Monitoring System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-a7F2pbKor4zjHV7vN0hjYA8akK2Dbf0
"""

# ============================================
# FINANCIAL FRAUD ANALYTICS & RISK MONITORING
# Complete Google Colab Implementation
# ============================================

# Step 1: Install required libraries (Colab specific)
!pip install scikit-learn imbalanced-learn xgboost plotly kaleido

# Step 2: Import all necessary libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime, timedelta
import warnings
warnings.filterwarnings('ignore')

# Machine Learning imports
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.ensemble import RandomForestClassifier, IsolationForest
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score, roc_curve, precision_recall_curve
from sklearn.cluster import DBSCAN

# For handling imbalanced data
from imblearn.over_sampling import SMOTE

# For time series
from scipy import stats

# For SQL simulation
import sqlite3

# Display settings
pd.set_option('display.max_columns', None)
plt.style.use('seaborn-v0_8-darkgrid')
sns.set_palette("husl")

# Step 3: Generate synthetic banking transaction data (realistic simulation)
np.random.seed(42)

def generate_fraud_data(n_transactions=50000):
    """Generate realistic banking transaction data with fraud patterns"""

    # Generate transaction IDs and timestamps
    transaction_ids = range(1, n_transactions + 1)
    timestamps = pd.date_range('2024-01-01', periods=n_transactions, freq='5min')

    # Generate customer IDs (5000 unique customers)
    customer_ids = np.random.randint(1, 5001, n_transactions)

    # Generate amounts (normal: small-medium; fraud: often larger)
    amounts = np.where(
        np.random.random(n_transactions) < 0.05,  # 5% potentially suspicious
        np.random.exponential(5000, n_transactions),  # Larger amounts
        np.random.exponential(500, n_transactions)    # Normal amounts
    )
    amounts = np.round(amounts, 2)

    # Transaction types
    transaction_types = np.random.choice(
        ['ONLINE', 'POS', 'ATM', 'TRANSFER', 'BILL_PAYMENT'],
        n_transactions,
        p=[0.4, 0.25, 0.15, 0.15, 0.05]
    )

    # Locations (with fraud hotspots)
    locations = np.where(
        np.random.random(n_transactions) < 0.03,
        np.random.choice(['Foreign_High_Risk', 'Unknown_IP', 'Darknet_Related'], n_transactions),
        np.random.choice(['USA', 'UK', 'Canada', 'Germany', 'France'], n_transactions)
    )

    # Time features
    hours = timestamps.hour
    is_weekend = (timestamps.dayofweek >= 5).astype(int)
    is_night = ((hours < 6) | (hours > 22)).astype(int)

    # Generate fraud labels (1=fraud, 0=legitimate)
    # Fraud patterns:
    # 1. High amount + night time + foreign location
    # 2. Multiple transactions in short time
    # 3. Unusual transaction type for customer

    fraud_probability = np.zeros(n_transactions)

    # Pattern 1: High amount fraud
    mask1 = (amounts > 5000) & (is_night == 1) & (locations != 'USA')
    fraud_probability[mask1] += 0.6

    # Pattern 2: Transfer fraud
    mask2 = (transaction_types == 'TRANSFER') & (amounts > 3000)
    fraud_probability[mask2] += 0.4

    # Pattern 3: Rapid succession pattern (simulated)
    mask3 = (amounts > 2000) & (np.random.random(n_transactions) < 0.05)
    fraud_probability[mask3] += 0.5

    # Generate final fraud labels
    fraud_labels = (fraud_probability + np.random.random(n_transactions) * 0.3) > 0.7
    fraud_labels = fraud_labels.astype(int)

    # Ensure reasonable fraud rate (around 5%)
    fraud_rate = fraud_labels.mean()
    if fraud_rate > 0.08:
        fraud_labels[np.where(fraud_labels == 1)[0][:int((fraud_rate - 0.05) * n_transactions)]] = 0
    elif fraud_rate < 0.02:
        additional_fraud = np.random.choice(n_transactions, int((0.05 - fraud_rate) * n_transactions), replace=False)
        fraud_labels[additional_fraud] = 1

    # Generate customer velocity features (transactions per hour)
    velocity = np.random.poisson(2, n_transactions)
    velocity[fraud_labels == 1] = np.random.poisson(8, fraud_labels.sum())

    # Additional features
    balance_before = np.abs(np.random.normal(5000, 3000, n_transactions))
    balance_after = balance_before - amounts
    balance_after[balance_after < 0] = 0

    df = pd.DataFrame({
        'transaction_id': transaction_ids,
        'timestamp': timestamps,
        'customer_id': customer_ids,
        'amount': amounts,
        'transaction_type': transaction_types,
        'location': locations,
        'hour': hours,
        'is_weekend': is_weekend,
        'is_night': is_night,
        'velocity_1h': velocity,
        'balance_before': balance_before,
        'balance_after': balance_after,
        'is_fraud': fraud_labels
    })

    return df

# Generate the dataset
print("Generating synthetic banking transaction data...")
df = generate_fraud_data(50000)
print(f"Dataset shape: {df.shape}")
print(f"Fraud rate: {df['is_fraud'].mean():.2%}")
print(f"Fraudulent transactions: {df['is_fraud'].sum():,}")
print(f"Legitimate transactions: {(~df['is_fraud'].astype(bool)).sum():,}")

# Step 4: Exploratory Data Analysis (EDA)
print("\n" + "="*60)
print("EXPLORATORY DATA ANALYSIS")
print("="*60)

# Basic statistics
print("\nBasic Statistics:")
print(df[['amount', 'balance_before', 'velocity_1h']].describe())

# Fraud analysis by transaction type
print("\nFraud Rate by Transaction Type:")
fraud_by_type = df.groupby('transaction_type')['is_fraud'].mean().sort_values(ascending=False)
print(fraud_by_type)

# Visualization
fig, axes = plt.subplots(2, 3, figsize=(15, 10))

# 1. Transaction amount distribution
ax1 = axes[0, 0]
for label, color in [(0, 'blue'), (1, 'red')]:
    subset = df[df['is_fraud'] == label]
    ax1.hist(subset['amount'], bins=50, alpha=0.7, label=f'Fraud={label}', color=color)
ax1.set_xlabel('Transaction Amount ($)')
ax1.set_ylabel('Frequency')
ax1.set_title('Transaction Amount Distribution')
ax1.legend()
ax1.set_xlim(0, 10000)

# 2. Fraud by hour
ax2 = axes[0, 1]
hourly_fraud = df.groupby('hour')['is_fraud'].mean()
ax2.plot(hourly_fraud.index, hourly_fraud.values, marker='o', linewidth=2)
ax2.set_xlabel('Hour of Day')
ax2.set_ylabel('Fraud Rate')
ax2.set_title('Fraud Rate by Hour of Day')
ax2.grid(True, alpha=0.3)

# 3. Transaction type comparison
ax3 = axes[0, 2]
fraud_by_type.plot(kind='bar', ax=ax3)
ax3.set_xlabel('Transaction Type')
ax3.set_ylabel('Fraud Rate')
ax3.set_title('Fraud Rate by Transaction Type')
ax3.set_xticklabels(ax3.get_xticklabels(), rotation=45)

# 4. Location-based fraud
ax4 = axes[1, 0]
location_fraud = df.groupby('location')['is_fraud'].mean().sort_values(ascending=False).head(10)
location_fraud.plot(kind='bar', ax=ax4)
ax4.set_xlabel('Location')
ax4.set_ylabel('Fraud Rate')
ax4.set_title('Top 10 Locations by Fraud Rate')
ax4.set_xticklabels(ax4.get_xticklabels(), rotation=45)

# 5. Amount vs Fraud
ax5 = axes[1, 1]
ax5.boxplot([df[df['is_fraud']==0]['amount'], df[df['is_fraud']==1]['amount']],
            labels=['Legitimate', 'Fraudulent'])
ax5.set_ylabel('Transaction Amount ($)')
ax5.set_title('Amount Distribution: Legitimate vs Fraudulent')
ax5.set_yscale('log')

# 6. Velocity correlation
ax6 = axes[1, 2]
velocity_by_fraud = [df[df['is_fraud']==0]['velocity_1h'], df[df['is_fraud']==1]['velocity_1h']]
ax6.boxplot(velocity_by_fraud, labels=['Legitimate', 'Fraudulent'])
ax6.set_ylabel('Transactions per Hour')
ax6.set_title('Transaction Velocity: Legitimate vs Fraudulent')

plt.tight_layout()
plt.show()

# Step 5: Feature Engineering
print("\n" + "="*60)
print("FEATURE ENGINEERING")
print("="*60)

# Create engineered features
df['amount_log'] = np.log1p(df['amount'])
df['balance_ratio'] = df['amount'] / (df['balance_before'] + 1)
df['balance_change'] = df['balance_before'] - df['balance_after']
df['hour_sin'] = np.sin(2 * np.pi * df['hour'] / 24)
df['hour_cos'] = np.cos(2 * np.pi * df['hour'] / 24)

# Rolling features (using time-based windows)
df = df.sort_values(['customer_id', 'timestamp'])
df['rolling_amount_mean_5'] = df.groupby('customer_id')['amount'].transform(
    lambda x: x.rolling(5, min_periods=1).mean()
)
df['rolling_amount_std_5'] = df.groupby('customer_id')['amount'].transform(
    lambda x: x.rolling(5, min_periods=1).std()
)
df['rolling_count_5'] = df.groupby('customer_id')['transaction_id'].transform(
    lambda x: x.rolling(5, min_periods=1).count()
)

# Encode categorical variables
le_type = LabelEncoder()
le_location = LabelEncoder()
df['transaction_type_encoded'] = le_type.fit_transform(df['transaction_type'])
df['location_encoded'] = le_location.fit_transform(df['location'])

print("New features created:")
print(f"- amount_log, balance_ratio, balance_change")
print(f"- hour_sin, hour_cos (cyclical time encoding)")
print(f"- rolling statistics (window=5 transactions)")
print(f"- Encoded transaction_type and location")

# Step 6: Anomaly Detection Pipelines
print("\n" + "="*60)
print("ANOMALY DETECTION PIPELINES")
print("="*60)

# Prepare features for ML models
feature_columns = ['amount', 'amount_log', 'balance_ratio', 'velocity_1h',
                   'is_night', 'is_weekend', 'hour_sin', 'hour_cos',
                   'rolling_amount_mean_5', 'rolling_amount_std_5',
                   'rolling_count_5', 'transaction_type_encoded', 'location_encoded']

X = df[feature_columns].fillna(0)
y = df['is_fraud']

# Standardize features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Split data
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.3, random_state=42, stratify=y)
print(f"Training set size: {len(X_train)}")
print(f"Test set size: {len(X_test)}")
print(f"Training fraud rate: {y_train.mean():.3f}")
print(f"Test fraud rate: {y_test.mean():.3f}")

# Apply SMOTE for class imbalance
smote = SMOTE(random_state=42, sampling_strategy=0.3)
X_train_resampled, y_train_resampled = smote.fit_resample(X_train, y_train)
print(f"\nAfter SMOTE - Training set size: {len(X_train_resampled)}")
print(f"After SMOTE - Fraud rate: {y_train_resampled.mean():.3f}")

# Model 1: Isolation Forest (Unsupervised Anomaly Detection)
print("\n" + "-"*40)
print("Model 1: Isolation Forest")
iso_forest = IsolationForest(contamination=0.05, random_state=42, n_estimators=100)
iso_forest.fit(X_train)
y_pred_iso = iso_forest.predict(X_test)
y_pred_iso = (y_pred_iso == -1).astype(int)

# Model 2: Random Forest (Supervised)
print("\n" + "-"*40)
print("Model 2: Random Forest")
rf_model = RandomForestClassifier(n_estimators=100, max_depth=10, random_state=42, class_weight='balanced')
rf_model.fit(X_train_resampled, y_train_resampled)
y_pred_rf = rf_model.predict(X_test)
y_pred_rf_proba = rf_model.predict_proba(X_test)[:, 1]

# Model 3: Logistic Regression with SMOTE
print("\n" + "-"*40)
print("Model 3: Logistic Regression")
lr_model = LogisticRegression(random_state=42, max_iter=1000, class_weight='balanced')
lr_model.fit(X_train_resampled, y_train_resampled)
y_pred_lr = lr_model.predict(X_test)
y_pred_lr_proba = lr_model.predict_proba(X_test)[:, 1]

# Model Evaluation
print("\n" + "="*60)
print("MODEL EVALUATION")
print("="*60)

# Evaluate Random Forest
print("\nRandom Forest Performance:")
print(classification_report(y_test, y_pred_rf, target_names=['Legitimate', 'Fraud']))
print(f"ROC-AUC Score: {roc_auc_score(y_test, y_pred_rf_proba):.4f}")

# Confusion Matrix Visualization
fig, axes = plt.subplots(1, 3, figsize=(15, 4))

models = [('Isolation Forest', y_pred_iso),
          ('Random Forest', y_pred_rf),
          ('Logistic Regression', y_pred_lr)]

for idx, (name, preds) in enumerate(models):
    cm = confusion_matrix(y_test, preds)
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', ax=axes[idx])
    axes[idx].set_title(f'{name}\nConfusion Matrix')
    axes[idx].set_xlabel('Predicted')
    axes[idx].set_ylabel('Actual')

plt.tight_layout()
plt.show()

# ROC Curves
plt.figure(figsize=(10, 6))
# Random Forest ROC
fpr_rf, tpr_rf, _ = roc_curve(y_test, y_pred_rf_proba)
auc_rf = roc_auc_score(y_test, y_pred_rf_proba)
plt.plot(fpr_rf, tpr_rf, label=f'Random Forest (AUC = {auc_rf:.3f})', linewidth=2)

# Logistic Regression ROC
fpr_lr, tpr_lr, _ = roc_curve(y_test, y_pred_lr_proba)
auc_lr = roc_auc_score(y_test, y_pred_lr_proba)
plt.plot(fpr_lr, tpr_lr, label=f'Logistic Regression (AUC = {auc_lr:.3f})', linewidth=2)

# Baseline
plt.plot([0, 1], [0, 1], 'k--', label='Random Classifier')

plt.xlabel('False Positive Rate', fontsize=12)
plt.ylabel('True Positive Rate', fontsize=12)
plt.title('ROC Curves - Fraud Detection Models', fontsize=14, fontweight='bold')
plt.legend(loc='lower right')
plt.grid(True, alpha=0.3)
plt.show()

# Step 7: SQL Database Simulation
print("\n" + "="*60)
print("SQL DATABASE SETUP & QUERIES")
print("="*60)

# Create SQLite database
conn = sqlite3.connect(':memory:')  # In-memory database
df.to_sql('transactions', conn, index=False, if_exists='replace')
print("Database created successfully!")

# SQL Queries for fraud analytics
queries = {
    "1. Suspicious High-Value Night Transactions": """
        SELECT COUNT(*) as fraud_count,
               SUM(amount) as total_amount,
               AVG(amount) as avg_amount
        FROM transactions
        WHERE is_night = 1 AND amount > 5000 AND is_fraud = 1
    """,

    "2. Top 10 Customers by Fraud Risk Score": """
        SELECT customer_id,
               COUNT(*) as total_trans,
               SUM(is_fraud) as fraud_trans,
               ROUND(100.0 * SUM(is_fraud) / COUNT(*), 2) as fraud_rate,
               SUM(amount) as total_fraud_amount
        FROM transactions
        GROUP BY customer_id
        HAVING fraud_trans > 0
        ORDER BY fraud_rate DESC
        LIMIT 10
    """,

    "3. Hourly Fraud Pattern Analysis": """
        SELECT hour,
               COUNT(*) as total_trans,
               SUM(is_fraud) as fraud_trans,
               ROUND(100.0 * SUM(is_fraud) / COUNT(*), 2) as fraud_rate
        FROM transactions
        GROUP BY hour
        ORDER BY hour
    """,

    "4. High Velocity Transactions (>10 per hour)": """
        SELECT customer_id,
               timestamp,
               velocity_1h,
               amount,
               is_fraud
        FROM transactions
        WHERE velocity_1h > 10
        ORDER BY velocity_1h DESC
        LIMIT 20
    """
}

for query_name, query in queries.items():
    print(f"\n{query_name}:")
    result = pd.read_sql_query(query, conn)
    print(result)

# Close connection
conn.close()

# Step 8: Real-time Risk Scoring Function
print("\n" + "="*60)
print("REAL-TIME RISK SCORING SYSTEM")
print("="*60)

def calculate_risk_score(transaction, rf_model, scaler):
    """
    Calculate real-time fraud risk score for a transaction
    """
    # Extract features
    risk_features = np.array([[
        transaction['amount'],
        np.log1p(transaction['amount']),
        transaction['amount'] / max(transaction['balance_before'], 1),
        transaction['velocity_1h'],
        transaction['is_night'],
        transaction['is_weekend'],
        np.sin(2 * np.pi * transaction['hour'] / 24),
        np.cos(2 * np.pi * transaction['hour'] / 24),
        transaction.get('rolling_amount_mean_5', transaction['amount']),
        transaction.get('rolling_amount_std_5', 0),
        transaction.get('rolling_count_5', 1),
        transaction['transaction_type_encoded'],
        transaction['location_encoded']
    ]])

    # Scale features
    risk_features_scaled = scaler.transform(risk_features)

    # Get fraud probability
    fraud_prob = rf_model.predict_proba(risk_features_scaled)[0, 1]

    # Determine risk level
    if fraud_prob < 0.3:
        risk_level = "LOW"
        action = "Approve"
    elif fraud_prob < 0.7:
        risk_level = "MEDIUM"
        action = "Review"
    else:
        risk_level = "HIGH"
        action = "Block & Alert"

    return {
        'fraud_probability': round(fraud_prob * 100, 2),
        'risk_level': risk_level,
        'recommended_action': action
    }

# Test the risk scoring system with sample transactions
test_transactions = [
    {'amount': 7500, 'balance_before': 15000, 'velocity_1h': 1, 'is_night': 1,
     'is_weekend': 0, 'hour': 3, 'transaction_type_encoded': 2, 'location_encoded': 5},
    {'amount': 150, 'balance_before': 5000, 'velocity_1h': 1, 'is_night': 0,
     'is_weekend': 0, 'hour': 14, 'transaction_type_encoded': 0, 'location_encoded': 0},
    {'amount': 12000, 'balance_before': 20000, 'velocity_1h': 8, 'is_night': 1,
     'is_weekend': 1, 'hour': 23, 'transaction_type_encoded': 3, 'location_encoded': 10}
]

print("\nRisk Assessment for Sample Transactions:")
for i, trans in enumerate(test_transactions, 1):
    risk = calculate_risk_score(trans, rf_model, scaler)
    print(f"\nTransaction {i}:")
    print(f"  Amount: ${trans['amount']:,.2f}")
    print(f"  Fraud Probability: {risk['fraud_probability']}%")
    print(f"  Risk Level: {risk['risk_level']}")
    print(f"  Action: {risk['recommended_action']}")

# Step 9: Feature Importance Analysis
print("\n" + "="*60)
print("FEATURE IMPORTANCE ANALYSIS")
print("="*60)

feature_importance = pd.DataFrame({
    'feature': feature_columns,
    'importance': rf_model.feature_importances_
}).sort_values('importance', ascending=False)

plt.figure(figsize=(10, 6))
plt.barh(feature_importance['feature'][:10], feature_importance['importance'][:10])
plt.xlabel('Importance Score')
plt.title('Top 10 Most Important Features for Fraud Detection')
plt.gca().invert_yaxis()
plt.tight_layout()
plt.show()

print("\nTop 5 Most Important Features:")
print(feature_importance.head())

# Step 10: Export Data for Power BI
print("\n" + "="*60)
print("EXPORTING DATA FOR POWER BI DASHBOARD")
print("="*60)

# Create summarized datasets for dashboard
dashboard_data = {
    'fraud_summary': df.groupby('timestamp').agg({
        'is_fraud': 'sum',
        'amount': 'sum',
        'transaction_id': 'count'
    }).reset_index(),

    'hourly_fraud': df.groupby('hour').agg({
        'is_fraud': ['count', 'sum', lambda x: (x.sum() / len(x)) * 100]
    }).round(2),

    'customer_risk': df.groupby('customer_id').agg({
        'is_fraud': 'sum',
        'amount': 'sum',
        'transaction_id': 'count'
    }).assign(risk_score = lambda x: x['is_fraud'] / x['transaction_id']).round(3)
}

# Save to CSV for Power BI
dashboard_data['hourly_fraud'].to_csv('hourly_fraud_patterns.csv')
df.to_csv('full_transaction_data.csv', index=False)
print("Data exported to CSV files for Power BI visualization:")
print("- full_transaction_data.csv")
print("- hourly_fraud_patterns.csv")

# Step 11: Generate Power BI Dashboard Code
print("\n" + "="*60)
print("POWER BI DASHBOARD CREATION GUIDE")
print("="*60)

power_bi_code = """
POWER BI DASHBOARD COMPONENTS:

1. DAX Measures to Create:

2. Visualizations:
- KPI Cards: Fraud Rate (%), Total Fraud Amount, Total Fraud Cases
- Line Chart: Fraud Trends over Time (daily/weekly)
- Bar Chart: Fraud by Transaction Type
- Map: Geographic Distribution of Fraud Attempts
- Table: High-Risk Transactions (risk score > 0.7)
- Gauge: Real-time Fraud Risk Level
- Scatter Plot: Amount vs. Velocity colored by Fraud Label
- Slicers: Date Range, Transaction Type, Location

3. Dashboard Layout:
Row 1: KPI Summary Cards
Row 2: Fraud Trend (Line) + Fraud by Type (Bar)
Row 3: Geographic Map + High-Risk Transactions Table
Row 4: Amount Distribution + Velocity Analysis
Footer: Real-time Alerts and Filters
"""

print(power_bi_code)

# Step 12: Alert System Simulation
print("\n" + "="*60)
print("REAL-TIME ALERT SYSTEM")
print("="*60)

class FraudAlertSystem:
 def __init__(self, threshold=0.85):
     self.threshold = threshold
     self.alerts = []

 def monitor_transaction(self, transaction, fraud_probability):
     if fraud_probability > self.threshold:
         alert = {
             'timestamp': datetime.now(),
             'customer_id': transaction.get('customer_id', 'N/A'),
             'amount': transaction.get('amount', 0),
             'fraud_probability': fraud_probability,
             'alert_level': 'CRITICAL'
         }
         self.alerts.append(alert)
         self.send_alert(alert)
         return True
     return False

 def send_alert(self, alert):
     print(f"""
     ⚠️  FRAUD ALERT ⚠️
     Time: {alert['timestamp']}
     Customer: {alert['customer_id']}
     Amount: ${alert['amount']:,.2f}
     Fraud Probability: {alert['fraud_probability']*100:.1f}%
     Action: BLOCK TRANSACTION IMMEDIATELY
     """)

 def get_alert_summary(self):
     return pd.DataFrame(self.alerts)

# Test alert system
alert_system = FraudAlertSystem(threshold=0.85)
print("\nMonitoring transactions for high-risk fraud...")
for i, trans in enumerate(test_transactions):
 risk = calculate_risk_score(trans, rf_model, scaler)
 is_alert = alert_system.monitor_transaction(trans, risk['fraud_probability']/100)
 if is_alert:
     print(f"Alert triggered for transaction {i+1}!")

# Final Summary
print("\n" + "="*60)
print("FRAUD ANALYTICS SYSTEM - DEPLOYMENT SUMMARY")
print("="*60)

summary_stats = {
 'Total Transactions Analyzed': len(df),
 'Total Fraudulent Transactions': df['is_fraud'].sum(),
 'Overall Fraud Rate': f"{df['is_fraud'].mean():.2%}",
 'Best Model Performance (AUC)': f"{auc_rf:.3f}",
 'Features Engineered': len(feature_columns),
 'High-Risk Customers Detected': df[df['is_fraud']==1]['customer_id'].nunique(),
 'Total Fraud Amount': f"${df[df['is_fraud']==1]['amount'].sum():,.2f}",
 'Average Fraud Amount': f"${df[df['is_fraud']==1]['amount'].mean():,.2f}"
}

for key, value in summary_stats.items():
 print(f"{key}: {value}")

print("\n✅ Fraud Analytics System Ready for Deployment!")
print("Components implemented: SQL Database, EDA, Feature Engineering,")
print("Anomaly Detection (Isolation Forest), Supervised Learning (Random Forest/LR),")
print("Real-time Risk Scoring, Alert System, and Power BI Integration.")